### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by MirayXS** [auguwu/auguwu#1]
# hi. 👋 

i just wanted to say that i like that you used the badges i used :)

also, i think they don't work, unfortunately, as dev.discordprofiles.me is still in development..

**Comment by rjm-codes** [comment]
What's the significance of "dev.discordprofiles.me" in relation to what badges Chris decided to use on his GitHub profile? And in what regard do they not work? I see them perfectly fine.

Interesting issue, I guess.

**Comment by MirayXS** [comment]
> What's the significance of "dev.discordprofiles.me" in relation to what badges Chris decided to use on his GitHub profile? And in what regard do they not work? I see them perfectly fine.
> 
> 
> 
> Interesting issue, I guess.

The badges used are from the dev.discordprofiles.me API. 

I also saw that they work for Chris, but for me not, so that’s why I made this issue

**Comment by rjm-codes** [comment]
They obviously work if I can see them... And you're probably better off asking the people who actually make the badges, reading documentation, or contacting Chris himself.

**Comment by MirayXS** [comment]
> They obviously work if I can see them...

They do work, but the API / Website is still in work, so for some people work. They do Not for me.

**Comment by rjm-codes** [comment]
So...?

**Comment by rjm-codes** [comment]
Figure out a solution, or use an alternative.

**Comment by MirayXS** [comment]
> Figure out a solution, or use an alternative.

I’ll just wait 😀

**Comment by auguwu** [comment]
hi yes sorry for not responding, I'll contact the developers since I know them so I'll check for a response. :)
I'll close the issue when I figure out an issue since it stopped working for me.

![proof](https://i.augu.dev/b52d.png)

**Comment by MirayXS** [comment]
> hi yes sorry for not responding, I'll contact the developers since I know them so I'll check for a response. :)
> 
> I'll close the issue when I figure out an issue since it stopped working for me.
> 
> 
> 
> ![proof](https://i.augu.dev/b52d.png)

Alright! I also contacted the devs, but they said that the app is still in development. Response may change for you? Let me know :)

**Comment by auguwu** [comment]
Issue has been fixed, closing issue.

![proof](https://i.augu.dev/c390.png)

**Comment by MirayXS** [comment]
Not working again; “ invalid “

**Comment by advaith1** [comment]
hi @MirayXS I'm the DiscordProfiles dev; I've publicly released the badge system at https://statusbadges.me
